services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-demo
    ports:
      - "8000:8000"
    environment:
      - SUMMARIZE_PROMPT=${SUMMARIZE_PROMPT}
      - HF_TOKEN=${HF_TOKEN}
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          cpus: '1'
          memory: 2G
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
